// Auto-generated by `npm run db:types` — do not edit manually.
// Run `npm run db:types` after schema changes to regenerate.
//
// Placeholder until Supabase local instance is running.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          roles: string[];
          rider_group_id: string | null;
          avatar_url: string | null;
          invite_status: string;
          medical_alerts: string | null;
          media_opt_out: boolean;
          invited_at: string | null;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          email: string;
          roles?: string[];
          rider_group_id?: string | null;
          avatar_url?: string | null;
          invite_status?: string;
          medical_alerts?: string | null;
          media_opt_out?: boolean;
          invited_at?: string | null;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          roles?: string[];
          rider_group_id?: string | null;
          avatar_url?: string | null;
          invite_status?: string;
          medical_alerts?: string | null;
          media_opt_out?: boolean;
          invited_at?: string | null;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      riders: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          group_id: string | null;
          date_of_birth: string | null;
          emergency_contact: string | null;
          medical_notes: string | null;
          media_opt_out: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          group_id?: string | null;
          date_of_birth?: string | null;
          emergency_contact?: string | null;
          medical_notes?: string | null;
          media_opt_out?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          group_id?: string | null;
          date_of_birth?: string | null;
          emergency_contact?: string | null;
          medical_notes?: string | null;
          media_opt_out?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          color: string;
          description: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          color?: string;
          description?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          color?: string;
          description?: string | null;
          sort_order?: number;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          type: string;
          description: string | null;
          location: string | null;
          map_url: string | null;
          starts_at: string;
          ends_at: string | null;
          rsvp_deadline: string | null;
          capacity: number | null;
          weather_notes: string | null;
          recurrence_rule: string | null;
          series_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          type: string;
          description?: string | null;
          location?: string | null;
          map_url?: string | null;
          starts_at: string;
          ends_at?: string | null;
          rsvp_deadline?: string | null;
          capacity?: number | null;
          weather_notes?: string | null;
          recurrence_rule?: string | null;
          series_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          type?: string;
          description?: string | null;
          location?: string | null;
          map_url?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          rsvp_deadline?: string | null;
          capacity?: number | null;
          weather_notes?: string | null;
          recurrence_rule?: string | null;
          series_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rsvps: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          rider_id: string | null;
          assigned_group_id: string | null;
          status: string;
          responded_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          rider_id?: string | null;
          assigned_group_id?: string | null;
          status: string;
          responded_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          user_id?: string;
          rider_id?: string | null;
          assigned_group_id?: string | null;
          status?: string;
          responded_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      has_role: {
        Args: { required_role: string };
        Returns: boolean;
      };
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_super_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
  };
};
